# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [6]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [15]:
A = np.arange(1, 16).reshape(3,5)

In [109]:
print(A)
print(A.ndim) #number of dimensions, row/column/depth
print(A.shape) # number of rows and columns
print(A.size) # number of elements
print(A.dtype) # data type

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2
(3, 5)
15
int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [232]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [234]:
subtraction = B - C
# Elementwise subtraction.

multiplication = B * C
# Elementwise multiplication.

matrix_multiplication = B @ C
# Matrix multiplication - multiply elements from first row with first column and add them together

print(subtraction)
print(multiplication)
print(matrix_multiplication)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [53]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
exponentiate = np.exp(B)
# Exponentiate each number elementwise (use the np.exp function).

min = np.min(B)
# Calculate the minimum value in the whole matrix.

min_eachrow = np.min(B, axis=1)
# Calculcate the minimum value in each row.

min_eachcolumn = np.min(B, axis=0)
# Calculcate the minimum value in each column.

index_min = np.argmin(B)
# Find the index value for the minimum value in the whole matrix (hint: use np.argmin).

index_min_eachrow = np.argmin(B, axis=1)
# Find the index value for the minimum value in each row (hint: use np.argmin).

sum_all = np.sum(B)
# Calculate the sum for all elements.

mean_eachcolumn = np.mean(B, axis=0)
# Calculate the mean for each column.

median_eachcolumn = np.median(B, axis=1)
# Calculate the median for each column.

print(exponentiate)
print(min)
print(min_eachrow)
print(min_eachcolumn)
print(index_min)
print(index_min_eachrow)
print(sum_all)
print(mean_eachcolumn)
print(median_eachcolumn)

[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[2. 5. 8.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [101]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [113]:
A[1]

array([ 6,  7,  8,  9, 10])

In [119]:
# Numpy assume that you want all the elements for the axes not specified. The example only specified the row axes and not the column axes and will therefor
# give you the elements for all the columns in that row. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [121]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [123]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [139]:
for i in A.flat:
# I would use the iterator attribute called flat which will iterate over all the elements of the array.
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [148]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [ ]:
# It creates an array with 30 elements. 
# It then reshapes the array into a new shape with 2 layers, 3 rows and 5 columns. In the example the column dimension is not specified, 
# the value "-1" means "whatever is needed", which means that the number of columns is decided automatically. 

# Having three axes means it has the dimensions of a cube with row, column and depth/layers. 
# Axis 0 = depth/layers
# Axis 1 = rows
# Axis 2 = columns

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [150]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [152]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [164]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [5]:
add_or_multiply = "multiply"

import numpy as np

A = np.array([4,3]).reshape(1,-1)
B = np.array([2,1]).reshape(-1,1)
# Create two matrices as input arguments

def add_mult_matrices(add_or_multiply, A, B):
    if isinstance(A, np.ndarray) and isinstance(B, np.ndarray):
        if add_or_multiply == "multiply":
            if A.shape == B.T.shape:          
                # perform matrix multiplication
                multiplication = A @ B
                return multiplication
            else: 
                return "The sizes do not conform for multiplication"
        elif add_or_multiply == "add":
            if A.size == B.size: 
                # perform element-wise addition
                addition = A + B
                return addition
            else: 
                return "The sizes do not conform for addition"
        else:
            return "Input must be numpy arrays"

result = add_mult_matrices(add_or_multiply, A, B)

print(result)
print(A.size)
print(B.size)
print(A.shape)
print(B.shape)

[[11]]
2
2
(1, 2)
(2, 1)


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [103]:
print("10.1.1.(a)", A.shape) # Vilken dimension har vektorn x?
print("10.1.1.(b)", A*5) # Berakna 5x.
print("10.1.1.(c)", A*3) # Berakna 3x.
print("10.1.1.(d)", A*5 + A*3) # Berakna 5x+3x
print("10.1.1.(e)", A*8) # Berakna 8x.
print("10.1.1.(f)", A*4 - A) # Berakna 4x-x
print("10.1.1.(g)", A.T.shape) # Berakna xT, vilken blir den nya dimensionen efter att transponeringen utförts?
print("10.1.1.(h)", "Definierat" if A.shape == A.T.shape else "Ej definierat") # Är x - xT definierat?
print("10.1.1.(i)", np.linalg.norm(A)) # Beräkna ||x||

10.1.1.(a) (2, 3)
10.1.1.(b) [[10 15 20]
 [25 20  5]]
10.1.1.(c) [[ 6  9 12]
 [15 12  3]]
10.1.1.(d) [[16 24 32]
 [40 32  8]]
10.1.1.(e) [[16 24 32]
 [40 32  8]]
10.1.1.(f) [[ 6  9 12]
 [15 12  3]]
10.1.1.(g) (3, 2)
10.1.1.(h) Inte definierat
10.1.1.(i) 8.426149773176359


In [105]:
v = np.array([3,7,0,11]).reshape(-1,1)
print("10.1.2.(a)", v.shape)
print("10.1.2.(b)", v*2)
print("10.1.2.(c)", v*5 + v*2)
print("10.1.2.(d)", v*4 - v*2)
print("10.1.2.(e)", v.T.shape)
print("10.1.2.(f)", np.linalg.norm(v))

10.1.2.(a) (4, 1)
10.1.2.(b) [[ 6]
 [14]
 [ 0]
 [22]]
10.1.2.(c) [[21]
 [49]
 [ 0]
 [77]]
10.1.2.(d) [[ 6]
 [14]
 [ 0]
 [22]]
10.1.2.(e) (1, 4)
10.1.2.(f) 13.379088160259652


In [107]:
v1 = np.array([4,3,1,5]).reshape(-1,1)
v2 = np.array([2,3,1,1]).reshape(-1,1)
print("10.1.3.(a)", np.linalg.norm(v1)) # Berakna ∥v1∥.
print("10.1.3.(b)", np.linalg.norm(v1-v2)) # Berakna ∥v1 − v2∥.

10.1.3.(a) 7.14142842854285
10.1.3.(b) 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [109]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1],[2]])
I = np.array([[1,0], [0,1]])
print("10.2.1.(a)", A*2)
print("10.2.1.(b)", B - A*2 if B.shape == A.shape else "Ej definierat") # Check if shape of array B = shape of array A
print("10.2.1.(c)", C*3 - E*2 if C.shape == E.shape else "Ej definierat") # Check if shape of array C = shape of array E
print("10.2.1.(d)", D*2 - C*3 if D.shape == C.shape else "Ej definierat") # Check if shape of array D = shape of array C
print("10.2.1.(e)", D.T + D*2 if D.T.shape == C.shape else "Ej definierat") # Check if shape of array D transposed = shape of array C
print("10.2.1.(f)", C.T*2 - D.T*2 if C.T.shape == D.T.shape else "Ej definierat") # Check if shape of array C transposed = shape of array D transposed
print("10.2.1.(g)", A.T - B if A.T.shape == B.shape else "Ej definierat") # Check if shape of array A transposed = shape of array B
print("10.2.1.(h)", A @ C if A.shape[1] == C.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array C
print("10.2.1.(i)", C @ D if C.shape[1] == D.shape[0] else "Ej definierat") # Checks if number of columns in array C = numbers of rows in array D
print("10.2.1.(j)", C @ B if C.shape[1] == B.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array B
print("10.2.1.(k)", C @ I if C.shape[1] == I.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array I
print("10.2.1.(l)", A @ B.T if A.shape[1] == B.T.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array B transposed

10.2.1.(a) [[ 4  2 -2]
 [ 2 -2  2]]
10.2.1.(b) [[ 0 -4  3]
 [ 0 -2 -4]]
10.2.1.(c) Ej definierat
10.2.1.(d) [[3 2]
 [2 3]]
10.2.1.(e) [[ 9 12]
 [12  9]]
10.2.1.(f) [[-4 -4]
 [-4 -4]]
10.2.1.(g) Ej definierat
10.2.1.(h) Ej definierat
10.2.1.(i) [[11 10]
 [10 11]]
10.2.1.(j) [[  8 -10  -3]
 [ 10  -8   0]]
10.2.1.(k) [[1 2]
 [2 1]]
10.2.1.(l) [[5 2]
 [7 4]]


In [101]:
A = np.array([[2, 3, 4], [5, 4, 1]])
print("10.2.2.", A @ A.T if A.shape[1] == A.T.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array A transposed

10.2.2 [[29 26]
 [26 42]]


In [181]:
A = np.array([[1, 2], [2, 4]])
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

print("10.2.3 True" if np.array_equal(A @ B, A @ C) else "10.2.3 False")
print("10.2.3 True" if np.array_equal(B @ A, C @ A) else "10.2.3 False")
print("10.2.3", A @ B if A.shape[1] == B.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array B
print("10.2.3", A @ C if A.shape[1] == C.shape[0] else "Ej definierat") # Checks if number of columns in array A = numbers of rows in array C
print("10.2.3", B @ C if B.shape[1] == C.shape[0] else "Ej definierat") # Checks if number of columns in array B = numbers of rows in array C


# Kontrollera räkneregler för matrismultiplikation (Sats 10.34)
print("10.34.(a) True" if np.array_equal((A @ B) @ C, A @ (B @ C)) else "10.34.(a) False")
print("10.34.(b) True" if np.array_equal(A @ (B + C), ((A @ B) + (A @ C))) else "10.34.(b) False")
print("10.34.(c) True" if np.array_equal((A + B) @ C, (A @ C) + (B @ C)) else "10.34.(c) False")
print("10.34.(d) True" if np.array_equal((2*A @ B), A @ (2*B)) else "10.34.(d) False")

10.2.3 True
10.2.3 False
10.2.3 [[ 4  7]
 [ 8 14]]
10.2.3 [[ 4  7]
 [ 8 14]]
10.2.3 [[8 8]
 [4 9]]
10.34.(a) True
10.34.(b) True
10.34.(c) True
10.34.(d) True


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [183]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [185]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [187]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [189]:
# you can use the base attribute to check if v1 and v2 is a view or a copy. The attribute returns the original array for a view and None for a copy. 
# v1 is a copy and v2 a view
# any changes made to a view is also reflected in the copy because they share the same memory, v2 is a view of the v1 copy.